
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "XCMV.h"

/*
* The configuration table for devices
*/

XCmv_Config XCmv_ConfigTable[XPAR_XCMV_NUM_INSTANCES] =
{
	{
		XPAR_XCMV_0_DEVICE_ID,
		XPAR_XCMV_0_S_AXI_BASEADDR
	}
};


