set_property SRC_FILE_INFO {cfile:C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/constrs_1/new/GPIO_LED.xdc rfile:../../../ScanEye_trigger.srcs/constrs_1/new/GPIO_LED.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/constrs_1/new/GPIO_SW.xdc rfile:../../../ScanEye_trigger.srcs/constrs_1/new/GPIO_SW.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/constrs_1/new/SPI_PMOD.xdc rfile:../../../ScanEye_trigger.srcs/constrs_1/new/SPI_PMOD.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/constrs_1/new/CLOCK_PMOD.xdc rfile:../../../ScanEye_trigger.srcs/constrs_1/new/CLOCK_PMOD.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/constrs_1/new/GPIO_OUT.xdc rfile:../../../ScanEye_trigger.srcs/constrs_1/new/GPIO_OUT.xdc id:5} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15        [get_ports "frame_req_0"]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8        [get_ports "gpio_led_tri_o[0]"]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports "gpio_led_tri_o[0]"]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5        [get_ports "gpio_led_tri_o[1]"]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports "gpio_led_tri_o[1]"]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12        [get_ports "gpio_led_tri_o[2]"]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports "gpio_led_tri_o[2]"]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16        [get_ports "gpio_led_tri_o[3]"]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports "gpio_led_tri_o[3]"]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17        [get_ports "gpio_led_tri_o[4]"]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports "gpio_led_tri_o[4]"]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17        [get_ports "gpio_led_tri_o[5]"]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports "gpio_led_tri_o[5]"]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15        [get_ports "power_good_0"]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15        [get_ports "t_last_0"]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18        [get_ports "gpio_sw_tri_i[0]"]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16        [get_ports "gpio_sw_tri_i[1]"]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19        [get_ports "gpio_sw_tri_i[2]"]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16        [get_ports "gpio_sw_tri_i[3]"]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8        [get_ports "spi_pmod_ss_io[0]"]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7        [get_ports "spi_pmod_io0_io"]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y7        [get_ports "spi_pmod_io1_io"]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6        [get_ports "spi_pmod_sck_io"]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15            [get_ports "CMV_CLK"]
set_property src_info {type:XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14        [get_ports "gpio_out_tri_o[0]"]
set_property src_info {type:XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14        [get_ports "gpio_out_tri_o[1]"]
set_property src_info {type:XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14        [get_ports "gpio_out_tri_o[2]"]
set_property src_info {type:XDC file:5 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17        [get_ports "gpio_out_tri_o[3]"]
set_property src_info {type:XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17        [get_ports "gpio_out_tri_o[4]"]
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17        [get_ports "gpio_out_tri_o[5]"]
