# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/GPIO_LED.xdc

# XDC: new/GPIO_SW.xdc

# XDC: new/SPI_PMOD.xdc

# XDC: new/CLOCK_PMOD.xdc

# XDC: new/GPIO_OUT.xdc

# Block Designs: bd/scaneye_trigger/scaneye_trigger.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger || ORIG_REF_NAME==scaneye_trigger} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_processing_system7_0_0/scaneye_trigger_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_processing_system7_0_0 || ORIG_REF_NAME==scaneye_trigger_processing_system7_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_xlconcat_0_0/scaneye_trigger_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_xlconcat_0_0 || ORIG_REF_NAME==scaneye_trigger_xlconcat_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_rst_ps7_0_100M_0/scaneye_trigger_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_rst_ps7_0_100M_0 || ORIG_REF_NAME==scaneye_trigger_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_ila_0_0/scaneye_trigger_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_ila_0_0 || ORIG_REF_NAME==scaneye_trigger_ila_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_axi_gpio_0_0/scaneye_trigger_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_axi_gpio_0_0 || ORIG_REF_NAME==scaneye_trigger_axi_gpio_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_axi_quad_spi_0_0/scaneye_trigger_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_axi_quad_spi_0_0 || ORIG_REF_NAME==scaneye_trigger_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_axi_timer_0_0/scaneye_trigger_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_axi_timer_0_0 || ORIG_REF_NAME==scaneye_trigger_axi_timer_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_clk_wiz_0_0/scaneye_trigger_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_clk_wiz_0_0 || ORIG_REF_NAME==scaneye_trigger_clk_wiz_0_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_xbar_0/scaneye_trigger_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_xbar_0 || ORIG_REF_NAME==scaneye_trigger_xbar_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_ps7_0_axi_periph_0/scaneye_trigger_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_ps7_0_axi_periph_0 || ORIG_REF_NAME==scaneye_trigger_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_XCMV_0_4/scaneye_trigger_XCMV_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_XCMV_0_4 || ORIG_REF_NAME==scaneye_trigger_XCMV_0_4} -quiet] -quiet

# IP: bd/scaneye_trigger/ip/scaneye_trigger_auto_pc_0/scaneye_trigger_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==scaneye_trigger_auto_pc_0 || ORIG_REF_NAME==scaneye_trigger_auto_pc_0} -quiet] -quiet

# XDC: c:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.gen/sources_1/bd/scaneye_trigger/scaneye_trigger_ooc.xdc
