# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/sources_1/bd/scaneye_trigger/ip/scaneye_trigger_processing_system7_0_0/scaneye_trigger_processing_system7_0_0.xci
# IP: The module: 'scaneye_trigger_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.gen/sources_1/bd/scaneye_trigger/ip/scaneye_trigger_processing_system7_0_0/scaneye_trigger_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'scaneye_trigger_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.srcs/sources_1/bd/scaneye_trigger/ip/scaneye_trigger_processing_system7_0_0/scaneye_trigger_processing_system7_0_0.xci
# IP: The module: 'scaneye_trigger_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Scanway/Vivado/ScanEye_trigger/ScanEye_trigger.gen/sources_1/bd/scaneye_trigger/ip/scaneye_trigger_processing_system7_0_0/scaneye_trigger_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'scaneye_trigger_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
